### ISSUE TITLE
Would this library support RX, pause 1 ms, then TX? Is it half-duplex?

### ISSUE THREAD

**Issue by josephernest** [flo90/USIUART#1]
I tried `SoftwareSerial` on ATtiny45 but it's really unreliable when we have many messages per second. Example application: a MIDI synthesizer sending 24 BeatClock messages per beat all the time + NoteOn/NoteOff messages.

Would your USIUART support something like this (here it's just a simple "echo" device: transmit to TX what has been received on RX)? :

```
byte buf1[64] = {0}; // buffer
byte num = 0;

void setup() {
  Serial2.begin(31250);
}
  
void loop() {
  while (Serial2.available()) {
    buf1[num] = Serial2.read();  // read everything available into a buffer
    num += 1;
  }
  delay(1);  // stop reading, wait 1 ms, and then write. Does this count as "half-duplex"?
  for (int i = 0; i < num; i++) {
    Serial2.write(buf1[i]);
  }
  num = 0;
}
```

**Comment by flo90** [comment]
Hi, unfortunately your delay does not count as half-duplex. The problem is that the USI module within the ATtiny has only one USI Data Register. As the same register is used for both, sending and receiving, only one action is possible at the same time (half-duplex). After the library is initialized, it starts listening to the RX wire until data is transmitted by calling usiuart_printStr(...). After a transmission has finished, the library starts to listen again. The function usiuart_getChar(...) only checks for new data in the buffer received before. It does not enable or disable receiving. If I am not wrong, this also applies to your used library.
Accordingly, you have to ask yourself the following question: Must the application receive data while it is sending data? If no, everything is fine. If yes, data sent to the ATtiny is lost if data is sent from the ATtiny at the same time.
Back to your example considering this library: During the delay(1) the ATtiny would still receive data which gets written to the buffer defined within this library (rxBuffer[RXBUFFERSIZE]). Remember that this buffer may overflow if you do not call usiuart_getChar(...) early enough or the buffer is not chosen big enough. After calling usiuart_printStr(...) (Serial2.write(...)) reception is blocked until the transmission is done.

**Comment by josephernest** [comment]
Thank you very much for your answer and for having looked at it.  
It seems I'll have no luck with a software serial (either Arduino's SoftwareSerial (="NewSoftSerial"), NeoSWSerial, AltSoftSerial, or yours) because doing a MIDI event processor really needs to be able to receive and transmit many messages at the same time (at 31250 baud).

In the meantime I tried with an ATmega328p and `Serial` (=HardwareSerial), and it's working great.
